steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "./"
      - "-t"
      - "us.gcr.io/dev-trials-q/training-python-app:v1.0"
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us.gcr.io/dev-trials-q/training-python-app:v1.0"
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=./deployment.yaml
      - --location=us-central1-c
      - --cluster=q-training