apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: training-node
  name: training-node
  namespace: q-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: training-node
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: training-node
      name: training-node
    spec:
      containers:
        - name: node-app
          image: us.gcr.io/dev-trials-q/training-node-app:v0.0
          ports:
            - containerPort: 5022
          livenessProbe:
            httpGet:
              port: 5022
              path: /
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 5022
              path: /
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: training-node
  namespace: q-training
spec:
  type: LoadBalancer
  selector:
    app: training-node
  ports:
    - port: 80
      targetPort: 5022